name: SDK Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    defaults:
      run:
        working-directory: ./src
    runs-on: ubuntu-20.04
    if: ${{ startsWith(github.ref, 'refs/tags/v') && github.repository == 'jellyfin/jellyfin-sdk-csharp' }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          ref: "master"

      - name: Setup .NET
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3
        with:
          dotnet-version: 7.0.x

      - name: Install dotnet-setversion
        run: dotnet tool install -g dotnet-setversion

      - name: Restore packages
        run: dotnet restore

      - name: Get Version
        id: version
        run: echo "number=$( echo ${{ github.event.release.tag_name }} | tr -d v )" >> $GITHUB_OUTPUT

      - name: Set project version
        run: setversion ${{steps.version.outputs.number}}

      - name: Generate sdk
        run: dotnet msbuild -target:GenerateSdk

      - name: Build packages
        run: dotnet build -c Release

      - name: Publish to nuget
        run: dotnet nuget push bin/Release/*.nupkg --api-key ${{ secrets.NUGET_APIKEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Commit new changes to the repo
        run: |
          git config user.name jellyfin-bot
          git config user.email team@jellyfin.org
          git pull
          git add .
          git commit --allow-empty -m "Update stable OpenAPI client"
          git push --force origin master
