name: SDK Publish (Unstable)

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-20.04
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          ref: "master"
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3
        with:
          dotnet-version: 7.0.x

      - name: Install dotnet-setversion
        run: dotnet tool install -g dotnet-setversion

      - name: Restore packages
        run: dotnet restore

      - name: Create new version string
        id: version
        run: echo "number=$(echo $(date +'%Y.%m.%d')-unstable.$(date +'%Y%m%d%H%M'))" >> $GITHUB_OUTPUT

      - name: Set project version
        run: setversion ${{ steps.version.outputs.number }}

      - name: Generate sdk
        run: dotnet msbuild -target:GenerateSdk-Unstable

      - name: Build packages
        run: dotnet build -c Release

      - name: Publish to nuget
        run: dotnet nuget push bin/Release/*.nupkg --api-key ${{ secrets.NUGET_APIKEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Commit new changes to the repo
        run: |
          git config user.name jellyfin-bot
          git config user.email team@jellyfin.org
          git checkout -B openapi-unstable
          git add .
          git commit --allow-empty -m "Update unstable OpenAPI client"
          git push --force origin openapi-unstable
